{% set name = "halide-python" %}
{% set version = "2019.08.27" %}
{% set sha256 = "2883622a952f411a8c8a0da60bb6f1277923c62549928be53a28ce61d72e8353" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/halide/Halide/archive/release_{{ version.replace('.', '_') }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ldflags.patch
    - imageio.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - halide =={{ version }}
    - zlib
  run:
    - halide =={{ version }}
    - zlib
    - python
    - numpy

test:
  requires:
    - imageio
  source_files:
    - python_bindings/apps
    - apps
  imports:
    - halide

about:
  home: http://halide-lang.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python bindings for Halide, a language for image processing and computational photography'

  description: |
    Halide is a programming language designed to make it easier to write
    high-performance data parallel processing code on modern machines. Its current front end is embedded in
    C++. Compiler targets include x86/SSE, ARM v7/NEON, CUDA, Hexagon DSP, and OpenCL.
  doc_url: http://halide-lang.org/docs/
  dev_url: https://github.com/halide/Halide

extra:
  recipe-maintainers:
    - jrk
    - minrk
    - steven-johnson
