travis:
  secure:
    BINSTAR_TOKEN: 00dbP1blee5f9V+JxjsLHgK8TknuD1m4Hvqz5w7Pqt+lszt7AT+UXhQnv74n99AICfhJ9/5hfZ/89AySZnaCePChVosT4TrKm6CI+Dbf3BytIukQIEOPUAL7gQE8Xrbyc7KdhqS2xzcawo/ahrLA9bvIFDcmwoHgLV2O5DBrfAHQtLyocUWykv5mg2P0N34EAQwO0cuicqRRfyW+vZlv0hqOjlAH2LKNur0KiP9jPQWD5qVU85UgVBVu3Ci+i0SaczLgs0be35DN4XW9ve4pwDJ0F2ndvJ4VdcTI0uLfUsBpvZ7M/hk4mvH+hwzxO6Bm7Ej4ps1K/6t1zfXSTIZnwmZJoLyi0fPkX3LqwMK1IIOAEyreEQWt0hZqDNzGzd0ONAg942IDgaj2oD69JhrUhl4+wT7LetASz39umD/ocMxggJ4eYXFWL9jPzrsTJ8yoN0al6JmAfrfh9dHirqln1wopDjmDfMURidh9gESljG1nd5DrmhasugoW6Ah58ug1s3N776rIwd2oPEcc5I8H+s/VRBK57ZPv0VAIkZtGMTlyd/CgDX1lqEzvxPuywgARP2T0NLu4PMKzhpQgvVyi5x/8S35w1dZFg11c5QlXetYRxt0W+fGlKaj2ZPeUWB2beSLdPcQU7RA+2H6fmp108hBEzzhR1LC51Fl/U2Jmgww=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
